### ISSUE TITLE
Relationships

### ISSUE THREAD

**Issue by smarbos** [baldosa/utodo#14]
Users can have tasks, boards and tags. 
Tasks must have owner and tags.
Tags must have an owner.
Boards must have tags and an owner.

**Comment by baldosa** [comment]
Sry I don't speak spanish

**Comment by smarbos** [comment]
> 

What about now?

**Comment by baldosa** [comment]
![image](https://user-images.githubusercontent.com/3511912/148408571-43951682-8c1b-4c3b-8d28-3a0cebffca64.png)
